# Generated by Django 3.1.1 on 2020-09-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=500)),
                ('short_url', models.CharField(max_length=10)),
                ('counter', models.IntegerField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='url',
        ),
    ]
