# Generated by Django 3.1.1 on 2020-09-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener_app', '0002_auto_20200929_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='counter',
            field=models.IntegerField(),
        ),
    ]
