# Generated by Django 3.1.1 on 2020-09-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener_app', '0003_auto_20200929_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortenedurl',
            old_name='short_url',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='shortenedurl',
            old_name='long_url',
            new_name='url',
        ),
    ]
